### ISSUE TITLE
The implementation about depth-wise conv

### ISSUE THREAD

**Issue by FengZicai** [dvlab-research/LargeKernel3D#1]
Hi, thanks for your work, I find that depth-wise conv is used. But this feature is not implemented in spconv and MinkowskiNet. Did you implement it yourself? Will the code of depth-wise conv be open?

**Comment by yukang2017** [comment]
Yes. We have implemented some attributes by ourselves and combined it into the spconv. We will release both our updated spconv and the codes for this paper in the next month. 

Thanks for your interest in our work.

**Comment by FengZicai** [comment]
I see, thanks for your reply.

**Comment by YehLi** [comment]
When will the code be released?

**Comment by yukang2017** [comment]
Sorry for the late reply. Thanks for your patience. It will be released in one or two weeks.

**Comment by vehxianfish** [comment]
> Sorry for the late reply. Thanks for your patience. It will be released in one or two weeks.

waiting  ...

**Comment by YehLi** [comment]
> > Sorry for the late reply. Thanks for your patience. It will be released in one or two weeks.
> 
> waiting ...

waiting ...

**Comment by vehxianfish** [comment]
> > > Sorry for the late reply. Thanks for your patience. It will be released in one or two weeks.
> > 
> > 
> > waiting ...
> 
> waiting ...
waiting ...

**Comment by vehxianfish** [comment]
> > > Sorry for the late reply. Thanks for your patience. It will be released in one or two weeks.
> > 
> > 
> > waiting ...
> 
> waiting ...

waiting

**Comment by yukang2017** [comment]
Sorry for keep you waiting. I have released the core spatial sparse conv in this repo [spconv-plus](https://github.com/dvlab-research/spconv-plus). The depth-wise conv (channel-wise group convolution) can also be found there.
