### ISSUE TITLE
runtime measurement

### ISSUE THREAD

**Issue by konyul** [dvlab-research/LargeKernel3D#2]
How did you validate runtime of your model??
Thank you

**Comment by yukang2017** [comment]
Thanks for your interest in our work. 
The runtime of our model is test on a NVIDIA 2080ti GPU. For nuScenes models, it is based on the original CenterPoint codebase. The implementation of SW-LK Conv is based on our improved version of spconv library for GPU acceleration. It will also be released.

**Comment by Qidian213** [comment]
When will the code be released? Thanks.

**Comment by yukang2017** [comment]
Thanks for your interest. I have released the core spatial sparse conv in this repo [spconv-plus](https://github.com/dvlab-research/spconv-plus). The overall training code for this paper will be released latter.
