### ISSUE TITLE
'trunc_normal_'  import error

### ISSUE THREAD

**Issue by fjzpcmj** [dvlab-research/LargeKernel3D#7]
https://github.com/dvlab-research/LargeKernel3D/blob/ca786a7a9fa6531db39da9b4eb0dc5149bbdc312/object-detection/det3d/models/backbones/scn_largekernel.py#L132
when runing detection with spatialgroupconvv2,  there will be error of "NameError: name 'trunc_normal_' is not defined"

**Comment by yukang2017** [comment]
Hi,

I fixed it with this line.

https://github.com/dvlab-research/LargeKernel3D/blob/518ddbe64aa79285fbe920f15ad7ca0207416ae4/object-detection/det3d/models/backbones/scn_largekernel.py#L10

Regards,
Yukang Chen

**Comment by fjzpcmj** [comment]
Dear Author, Thanks for your reply. I am training detection model with 
config "nusc_centerpoint_voxelnet_0075voxel_fix_bn_z_largekernel3d_large,py" in two V100 GPUs.  The conv type is 'spatialgroupconvv2'. It seems that it will cost 12days to train the model with 20 epochs. is this normal？It will be very nice if you can share your traning logs.

here is my traing log:
2023-05-08 19:00:44,415 - INFO - Epoch [1/20][510/30895]        lr: 0.00010, eta: 11 days, 17:20:45, time: 1.361, data_time: 0.121, transfer_time: 0.019, forward_time: 0.327, loss_parse_time: 0.001 memory: 7336,
